[tool.pytest.ini_options]
asyncio_mode = "auto"
markers = ["serial"]

[tool.ruff.lint.per-file-ignores]
# F401 F811 breaks with importing pytest fixtures
"test_*" = ["F401", "F811"]

#"__init__.py" = ["F401"]

